export const allIcons = {
  "01d": require("../Assets/clear.png"),
  "01n": require("../Assets/clear.png"),
  "02d": require("../Assets/cloud.png"),
  "02n": require("../Assets/cloud.png"),
  "03d": require("../Assets/cloud.png"),
  "03n": require("../Assets/cloud.png"),
  "04d": require("../Assets/drizzle.png"),
  "04n": require("../Assets/drizzle.png"),
  "09d": require("../Assets/rain.png"),
  "09n": require("../Assets/rain.png"),
  "10d": require("../Assets/rain.png"),
  "10n": require("../Assets/rain.png"),
  "13d": require("../Assets/snow.png"),
  "13n": require("../Assets/snow.png"),
};
